services:
  - type: web
    name: rainfall-prediction
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn rainfall_prediction:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
